# Allows for the definition of PR and Issue /commands
name: '📟 Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@987f20aa35d3a6c9b3091616c9b3488a3ea897dc # master
    secrets:
      token: ${{ secrets.JF_BOT_TOKEN }}
